name: "SmartThings Edge Development Deployment"
run-name: "${{ github.actor }} deploying to development channel"
on:
  push:
    branches:
      - develop
jobs:
  deploy-dev:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: "SmartThings CLI"
        uses: "actions/setup-node@v2"
      - run: "npm install --global @smartthings/cli"

      - name: "Upgrade Edge Drivers"
        uses: "actions/checkout@v3"
      - run: |
          DRIVERS_PATH=${{ github.workspace }}/zigbee;
          TARGET_CHANNEL=${{ secrets.ST_CHANNEL_DEVELOP }};
          TOKEN=${{ secrets.ST_PAT }};

          ./deploy.sh $DRIVERS_PATH $TARGET_CHANNEL $TOKEN;
